# Generated by Django 2.2.16 on 2020-09-16 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketDeburring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterDeburring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='thermaldeburrer',
            name='basket_deburring',
        ),
        migrations.AddField(
            model_name='thermaldeburrer',
            name='parameter_deburring',
            field=models.ManyToManyField(to='machines.ParameterDeburring'),
        ),
        migrations.AddField(
            model_name='thermaldeburrer',
            name='basket_deburring',
            field=models.ManyToManyField(to='machines.BasketDeburring'),
        ),
    ]
