# Generated by Django 2.2.16 on 2020-09-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20200916_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermaldeburrer',
            name='basket_deburring',
            field=models.ManyToManyField(blank=True, to='machines.BasketDeburring'),
        ),
        migrations.AlterField(
            model_name='thermaldeburrer',
            name='parameter_deburring',
            field=models.ManyToManyField(blank=True, to='machines.ParameterDeburring'),
        ),
    ]
