# Generated by Django 2.2.16 on 2020-09-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_thermaldeburring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThermalDeburring',
        ),
    ]
