# Generated by Django 2.2.16 on 2020-10-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_delete_thermaldeburring'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketdeburring',
            name='image',
            field=models.ImageField(blank=True, upload_to='baskets'),
        ),
    ]
