# Generated by Django 2.2.16 on 2020-09-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200913_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
