# Generated by Django 2.2.16 on 2020-09-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200913_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.SlugField(),
        ),
    ]
