# Generated by Django 2.2.16 on 2020-09-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200913_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.SlugField(unique=True),
        ),
    ]
