# Generated by Django 2.2.16 on 2020-09-15 16:33

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200915_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermaldeburring',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='code.code'),
            preserve_default=False,
        ),
    ]
