# Generated by Django 2.2.16 on 2020-09-15 16:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_thermaldeburring_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermaldeburring',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='code'),
        ),
    ]
