# Generated by Django 2.2.16 on 2020-09-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200915_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thermaldeburring',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='thermaldeburring',
            name='code',
        ),
        migrations.RemoveField(
            model_name='thermaldeburring',
            name='parameter',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='ThermalDeburring',
        ),
    ]
