# Generated by Django 2.2.16 on 2020-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200916_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, upload_to='articles'),
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, upload_to='articles'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, upload_to='articles'),
        ),
        migrations.AddField(
            model_name='article',
            name='image4',
            field=models.ImageField(blank=True, upload_to='articles'),
        ),
    ]
