# Generated by Django 2.2.16 on 2020-10-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200919_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['code']},
        ),
    ]
