# Generated by Django 2.2.16 on 2020-12-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20201214_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pallet',
            options={'ordering': ['-created_date']},
        ),
    ]
