# Generated by Django 2.2.16 on 2020-12-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_article_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='for_thermal_deburring',
        ),
        migrations.AddField(
            model_name='article',
            name='for_thermal_deburring',
            field=models.BooleanField(default=True),
        ),
    ]
