# Generated by Django 2.2.16 on 2020-12-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20201220_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pallet',
            options={'ordering': ['-created_date']},
        ),
    ]
