# Generated by Django 2.2.16 on 2021-01-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20201221_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
