# Generated by Django 2.2.16 on 2021-01-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_article_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
