# Generated by Django 2.2.16 on 2021-01-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_pallet_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
