# Generated by Django 2.2.16 on 2021-01-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20210129_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
