# Generated by Django 2.2.16 on 2021-02-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20210221_1515'),
        ('articles', '0029_auto_20210131_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department'),
        ),
    ]
