# Generated by Django 2.2.16 on 2021-03-08 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0031_pallet_thermal_deburred'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='employee_thermal_deburring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pallet_thermal_deburred', to=settings.AUTH_USER_MODEL),
        ),
    ]
