# Generated by Django 2.2.16 on 2021-03-08 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_pallet_employee_thermal_deburring'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='thermal_deburred_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
