# Generated by Django 2.2.16 on 2021-03-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_auto_20210308_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='weight_thermal_deburred_no_ok',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
