# Generated by Django 2.2.16 on 2021-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_pallet_weight_thermal_deburred_no_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='for_thermal_deburring',
            field=models.BooleanField(default=False),
        ),
    ]
