# Generated by Django 2.2.16 on 2021-03-24 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zamak', '0002_auto_20201007_2046'),
        ('articles', '0036_auto_20210319_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='zamak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zamak.Zamak'),
        ),
    ]
