# Generated by Django 2.2.16 on 2020-10-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamak',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
