# Generated by Django 2.2.16 on 2020-09-16 17:03

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0013_auto_20200916_1649'),
        ('machines', '0005_delete_thermaldeburring'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalDeburring',
            fields=[
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.Article')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='code')),
                ('basket_deburring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.BasketDeburring')),
                ('parameter_deburring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.ParameterDeburring')),
            ],
        ),
    ]
