# Generated by Django 2.2.16 on 2020-10-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermaldeburring',
            name='done_article',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
