# Generated by Django 2.2.16 on 2020-09-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermaldeburring',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thermaldeburring',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
