# Generated by Django 2.2.16 on 2020-11-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_thermaldeburring_done_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermaldeburring',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
