# Generated by Django 2.2.16 on 2020-12-07 08:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201126_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thermaldeburring',
            old_name='code',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='thermaldeburring',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='article'),
        ),
    ]
