# Generated by Django 2.2.16 on 2020-12-08 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201207_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thermaldeburring',
            options={'ordering': ['article__code']},
        ),
    ]
