# Generated by Django 2.2.16 on 2020-12-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201208_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thermaldeburring',
            name='done_article',
        ),
    ]
