# Generated by Django 2.2.16 on 2020-12-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_thermaldeburring_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palletthermaldeburred',
            options={'ordering': ['-thermal_deburred_date']},
        ),
    ]
