# Generated by Django 2.2.16 on 2021-01-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20201222_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletthermaldeburred',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
