# Generated by Django 2.2.16 on 2021-01-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_palletthermaldeburred_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletthermaldeburred',
            name='quantity_no_ok',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
