# Generated by Django 2.2.16 on 2021-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_palletthermaldeburred_quantity_no_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletthermaldeburred',
            name='quantity_no_ok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
