# Generated by Django 2.2.16 on 2021-01-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20210129_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletthermaldeburred',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
