# Generated by Django 2.2.16 on 2021-02-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_palletthermaldeburred_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletthermaldeburred',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
